# ===============================
# Build
# ===============================
FROM node:20-alpine AS builder

WORKDIR /app

# Variável pública do Vite
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

COPY package*.json ./
RUN npm ci

COPY . .

# Build do dashboard
RUN npm run build


# ===============================
# Runtime (Nginx)
# ===============================
FROM nginx:alpine

# Remove config default
RUN rm /etc/nginx/conf.d/default.conf

# Config do dashboard
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copia build estático
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]