# ===============================
# Base
# ===============================
FROM node:20-alpine AS base

WORKDIR /app

# ===============================
# Dependencies
# ===============================
FROM base AS deps

COPY package*.json ./
RUN npm ci

# ===============================
# Build
# ===============================
FROM base AS builder

# DECLARA O ARG (vem do docker-compose)
ARG NEXT_PUBLIC_API_URL

# TRANSFORMA EM ENV PARA O NEXT USAR NO BUILD
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NODE_ENV=production

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build do Next.js
RUN npm run build

# ===============================
# Runtime
# ===============================
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

# Apenas arquivos necessários para runtime
COPY --from=builder /app/package.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/next.config.* ./

EXPOSE 3000

CMD ["npm", "run", "start"]